feat: 完成我的账户UI
codemate-oj/codemate-fe pull request #42
Opened 2024-07-01 06:44 UTC by 21liyuqing

feat: 完成我的账户UI

2024-07-02 16:55 UTC, KiritoKing requested changes
有些细节规范注意一下

2024-07-02 16:55 UTC, KiritoKing commented on README.md
为啥动这个？

2024-07-02 16:55 UTC, KiritoKing commented on src/app/user/(center)/wallet/Overview.style.css
非定义antd的情况下 一定要用css的话就用module css 不要全局

2024-07-02 16:55 UTC, KiritoKing commented on src/app/user/(center)/wallet/Overview.tsx
不要在app里定义组件 移动到components的对应文件夹里

2024-07-03 02:24 UTC, 21liyuqing commented on README.md
可能是我看规范时候不小心回车或者空格了然后没取消一并提交了上去

2024-07-04 18:11 UTC, KiritoKing submitted a review, later dismissed

2024-07-04 18:12 UTC, merged