feat: ranking页面编写
codemate-oj/codemate-fe pull request #50
Opened 2024-07-14 07:00 UTC by Lhk0001

ranking，总榜页面

2024-07-15 06:15 UTC, KiritoKing requested changes

2024-07-15 06:15 UTC, KiritoKing commented on src/components/ranking/ranking-scoreboard.tsx
> +  const defaultObj = {
闭包无关的值移动到函数外

2024-07-15 06:15 UTC, KiritoKing commented on src/components/ranking/ranking-scoreboard.tsx
> +  udocs?.forEach((item: itemType, index: number) => {
副作用不能这么写 useEffect或者useMemo 二选一吧

2024-07-15 06:15 UTC, KiritoKing commented on src/components/ranking/tree-selelctor.tsx
> +  const [rankBy, setRankBy] = useUrlParamState("rankBy", "all");
你这样写确定你从url进来能复原状态？

2024-07-17 15:10 UTC, Lhk0001 commented on src/components/ranking/tree-selelctor.tsx
> +  const [rankBy, setRankBy] = useUrlParamState("rankBy", "all");
这个url的现在参数只有cpp和py和all和那个标签选择不对应，

2024-07-21 07:12 UTC, KiritoKing requested changes

2024-07-21 07:12 UTC, KiritoKing commented on src/components/ranking/ranking-scoreboard-table.tsx
> +      <div className="font-bold"></div>
这玩意儿是啥

2024-07-21 07:12 UTC, KiritoKing commented on src/components/ranking/ranking-scoreboard.tsx
> +  const { udocs, rpInfo } = data || { udocs: undefined, rpInfo: undefined };
为什么这里要添加副作用？

2024-07-21 07:12 UTC, KiritoKing commented on src/components/ranking/ranking-scoreboard.tsx
> +    udocs?.forEach((item: itemType, index: number) => {
直接写在useRequest里一次性处理好

2024-07-26 18:26 UTC, KiritoKing requested changes
再看看吧 怎么merge错误都带上来了

2024-08-18 13:28 UTC, KiritoKing approved these changes

2024-08-18 13:29 UTC, merged